spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: ${env.FIAP_USERNAME}
    password: ${env.FIAP_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true